### ISSUE TITLE
Not working with Spigot 1.8.8

### ISSUE THREAD

**Issue by Rodrogamby** [AnOrdinaryDev/RandomTP#1]
Hello, I'm using this plugin, but it isn't working at all on 1.8.8, every time I use the **/rtp tp Survival Xnumber** command, it says:  Couldn't find a location.
Any of the randomtp plugins out there have ever worked for me, I'd like to get this fixed as soon as possible. Thank you 👍 & have a nice day.
PD: Yes, I am using Vault.
And here's my console log:
[02:41:58] [Server thread/INFO]: Rodro issued server command: /rtp
[02:42:04] [Server thread/INFO]: Rodro issued server command: /rtp gui
[02:42:11] [Server thread/WARN]: [RandomTP-Reborn] Task #599 for RandomTP-Reborn v1.9 generated an exception
java.lang.NullPointerException
	at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[02:42:11] [Server thread/WARN]: [RandomTP-Reborn] Task #599 for RandomTP-Reborn v1.9 generated an exception
java.lang.NullPointerException
	at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
And it goes like that, over and over.

**Comment by Rodrogamby** [comment]
Dead resource
